<?php

namespace App\Http\Livewire\Admin;

use App\Models\Department;
use Livewire\Component;
use Livewire\WithPagination;

class DepartmentTable extends Component
{

    public $dept_id="no";
    public $dateorder="no";
    public $search="";
    public $showform=0;
    public $deleteDept="no";
    public $paginate_num=20;

    // public function getQueryString()
    // {
    //     return ['search'=>$this->search,'page'=>$this->page,'dept_id'=>$this->dept_id]; // TODO: Change the autogenerated stub
    // }

    // protected $queryString=['search','page','dept_id'];



    use WithPagination;
    public function render()
    {

            $departments=Department::withCount('products as products_count')
            ->where('name','LIKE','%'.$this->search."%")
            ->orderBy('updated_at','desc')->
            paginate($this->paginate_num);



           return view('admin.department.department-table',compact('departments'))->layout('components.dashboard.index');

        

    }



    public function setDept_id($dept_id){
        $this->dept_id=$dept_id;
        $this->showform=1;
    }
    public function cancelEdit(){
        $this->dept_id="no";
        $this->showform=0;
    }

    public  function setDeleteDept($idd){
        $this->deleteDept=$idd;
    }

    public function cancelDelete(){
        $this->deleteDept="no";
    }
    public function DeleteDept(){

        if($this->deleteDept!="no") {
        $dept=    Department::find($this->deleteDept);

        $dept->update([
            'active'=>true
        ]);

            session()->flash('statt','ok');
            session()->flash('message','تم الحذف');
            $this->deleteDept="no";

        }
    }
    public function deletePro($id){
        $dept=    Department::find($id);

        $dept->update([
            'active'=>!$dept->active
        ]);

    }
 


}
